services:
  - type: web
    name: fb-auto-commenter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: FB_APP_ID
        value: your_facebook_app_id
      - key: FB_APP_SECRET
        value: your_facebook_app_secret
